paths:
  input_file: "data/input/actual_data.csv" 
  output_db: "data/output/preferred_db_engine.db
  log_file: "logs/etl_log.log"

database:
  table_name: "processed_sales"

logging:
  level: "INFO"
